---
- hosts: all
  become: yes

  tasks:
  - name: Install 7zip from a network share specifying the credentials
   win_package:
     path: \\domain\programs\7z.exe
     product_id: 7-Zip
     arguments: /S
     state: present
