---
- hosts: all
  become: yes
  become_user: Administrator

#- name: Hello World Sample
#  hosts: all
#  tasks:
#    - name: Hello Message
#      debug:
#        msg: "Hello Suriya!"

 tasks:
- name: "Install Microsoft .NET Framework 4.5.2."
  win_package:
    path: "https://download.microsoft.com/download/E/2/1/E21644B5-2DF2-47C2-91BD-63C560427900/NDP452-KB2901907-x86-x64-AllOS-ENU.exe"
    product_id: "{26784146-6E05-3FF9-9335-786C7C0FB5BE}"
    register: dotnet452_exe

- name: Install 7zip from a network share specifying the credentials
  win_package:
    path: \\domain\programs\7z.exe
    product_id: 7-Zip
    arguments: /S
    state: present
