---
- hosts: all
  become: yes

  tasks:
  - name: Install Microsoft NET Framework
    win_package:
      path: "http://path/to/dotNetFramework4.6.1.exe"
      product_id: '{BD6F5371-DAC1-30F0-9DDE-CAC6791E28C3}'
      register: dotnetfx_exe
      arguments: /q /norestart
